[env]
_.file = [
  ".env",
  ".env.local"
]

[tools]
node = "latest"
aube = "latest"
viteplus = "latest"

[tasks.dev]
raw_args = true
run = "vp dev"

[tasks.test]
raw_args = true
run = "vp test"

[tasks.vp]
raw_args = true
run = "vp"

[tasks.aube]
raw_args = true
run = "aube"

[tasks.aubr]
raw_args = true
run = "aubr"

[tasks.aubx]
raw_args = true
run = "aubx"
