[env]
_.file = [
  ".env",
  ".env.local"
]

[tools]
node = "latest"
pnpm = "latest"
viteplus = "latest"

[tasks.dev]
raw_args = true
run = "vp dev"

[tasks.test]
raw_args = true
run = "vp test"

[tasks.pnpm]
raw_args = true
run = "pnpm"

[tasks.pnpx]
raw_args = true
run = "pnpx"
